from networks.Vnet import Vnet as vnet
from networks.Unet import Unet as unet
from networks.Vnet_4out import Vnet as vnet4out
from networks.Unet_4out import Unet as unet4out
from networks.Unetpp import Unetpp as unetpp
from networks.AttUnet import AttUnet as attunet
from networks.SwinUnet.vision_transformer import SwinUnet as swinunet
from networks.InceptionSwinUnet.InceptionSwinUnet_v1 import InceptionSwinUnet_from_config as isunetv1
from networks.InceptionSwinUnet.InceptionSwinUnet_v2 import InceptionSwinUnet_from_config as isunetv2
from networks.InceptionSwinUnet.InceptionSwinUnet_v3 import InceptionSwinUnet_from_config as isunetv3
from networks.InceptionSwinUnet.InceptionSwinUnet_v2_4out import InceptionSwinUnet_from_config as isunetv4
from networks.InceptionSwinUnet.InceptionSwinUnet_v3_4out import InceptionSwinUnet_from_config as isunetv5
